Prepare for upstream changes.
Summary:
Current clang's RecursiveASTVisitor API has changed. To make it easier to update in the future, we'll update our code now (especially given that doing so doesn't break any tests).

Without this change, we fail to compile:
```
kythe/cxx/indexer/cxx/IndexerASTHooks.h:221:12: error: no matching member function for call to 'TraverseNode'
    return TraverseNode(StmtNode, &VisitorBase::TraverseStmt);
           ^~~~~~~~~~~~
kythe/cxx/indexer/cxx/IndexerASTHooks.h:168:8: note: candidate template ignored: failed template argument deduction
  bool TraverseNode(T *Node, bool (VisitorBase::*traverse)(T *)) {
       ^
1 error generated.
```

This happened due to Clang commit 89d5b46c217bb7fd5d23e92def8f9a6edd57090a. The change mirrors the change that commit makes to ParentMapASTVisitor.

Reviewers: schroederc, fromberger

Reviewed By: schroederc, fromberger

Differential Revision: https://phabricator-dot-kythe-repo.appspot.com/D625